### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by svenstaro** [kazan-3d/kazan#2]
Hey, getting this on Arch Linux.
[log.txt](https://github.com/kazan-3d/kazan/files/1287514/log.txt)

clang --version
clang version 4.0.1 (tags/RELEASE_401/final)

I believe it's probably the version of libstdc++ I'm using which is from gcc 7.2.

**Comment by programmerjake** [comment]
I tested the fix in an Ubuntu Artful chroot, that has gcc 7.2.
